# Generated by Django 5.1.7 on 2025-05-19 06:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(blank=True, null=True, upload_to='berita/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('mapel', models.CharField(max_length=100)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='guru/')),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('kelas', models.CharField(max_length=20)),
                ('alamat', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='siswa/')),
            ],
        ),
        migrations.CreateModel(
            name='JadwalSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('mapel', models.CharField(max_length=100)),
                ('kelas', models.CharField(max_length=20)),
                ('guru', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('siswa', 'Siswa')], default='siswa', max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
