# Generated by Django 4.2.7 on 2025-05-21 16:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('isi', models.TextField()),
                ('gambar', models.ImageField(upload_to='berita/')),
                ('tanggal', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.ImageField(upload_to='galeri/')),
                ('keterangan', models.TextField(blank=True, null=True)),
                ('tanggal_upload', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nip', models.CharField(max_length=50, unique=True)),
                ('mapel', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('nis', models.CharField(max_length=50, unique=True)),
                ('kelas', models.CharField(choices=[('1', 'Kelas 1'), ('2', 'Kelas 2'), ('3', 'Kelas 3'), ('4', 'Kelas 4'), ('5', 'Kelas 5'), ('6', 'Kelas 6')], max_length=20)),
                ('alamat', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('guru', 'Guru'), ('siswa', 'Siswa')], max_length=10)),
                ('kelas', models.CharField(blank=True, max_length=2, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JadwalSiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hari', models.CharField(choices=[('Senin', 'Senin'), ('Selasa', 'Selasa'), ('Rabu', 'Rabu'), ('Kamis', 'Kamis'), ('Jumat', 'Jumat'), ('Sabtu', 'Sabtu')], max_length=20)),
                ('jam_mulai', models.TimeField()),
                ('jam_selesai', models.TimeField()),
                ('mapel', models.CharField(choices=[('Bahasa Indonesia', 'Bahasa Indonesia'), ('Matematika', 'Matematika'), ('Ilmu Pengetahuan Alam', 'Ilmu Pengetahuan Alam'), ('Ilmu Pengetahuan Sosial', 'Ilmu Pengetahuan Sosial'), ('Pendidikan Pancasila dan Kewarganegaraan', 'PPKn'), ('Pendidikan Agama', 'Pendidikan Agama'), ('Seni Budaya dan Prakarya', 'SBdP'), ('Pendidikan Jasmani, Olahraga, dan Kesehatan', 'PJOK'), ('Bahasa Inggris', 'Bahasa Inggris'), ('Muatan Lokal', 'Muatan Lokal')], max_length=100)),
                ('kelas', models.CharField(choices=[('1', 'Kelas 1'), ('2', 'Kelas 2'), ('3', 'Kelas 3'), ('4', 'Kelas 4'), ('5', 'Kelas 5'), ('6', 'Kelas 6')], max_length=20)),
                ('siswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='web.siswa')),
            ],
        ),
    ]
